/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsWasmModule {
  bytecode: Buffer
  exports: Array<string>
  imports: Array<string>
  functions: Array<string>
  hasMemory: boolean
}

export interface JsExecutionResult {
  success: boolean
  result?: string
  error?: string
  memoryUsage: number
  executionTimeMs: number
}

export interface JsHotReloadResult {
  success: boolean
  preservedState: boolean
  ffiBindingsPreserved: boolean
  error?: string
  affectedExports: Array<string>
}

export interface JsMemoryStats {
  totalPages: number
  usedPages: number
  maxPages?: number
  growthAllowed: boolean
  bytesPerPage: number
  activeAllocations: number
  fragmentationRatio: number
  totalAllocatedBytes: number
  peakMemoryUsage: number
}

export interface JsMemoryAllocation {
  success: boolean
  allocationId?: string
  offset?: number
  size?: number
  error?: string
}

export interface JsFFIBinding {
  name: string
  bindingType: string
  isAsync: boolean
  paramTypes: Array<string>
  resultTypes: Array<string>
  preserveState: boolean
}

export interface JsFFICallResult {
  success: boolean
  result?: string
  error?: string
  executionTimeMs: number
  statePreserved: boolean
}

export interface JsValueConversion {
  sourceValue: string
  sourceType: string
  targetType: string
  conversionOptions?: JsConversionOptions
}

export interface JsConversionOptions {
  strictTyping: boolean
  allowLossyConversion: boolean
  useCache: boolean
  validateRanges: boolean
  preservePrecision: boolean
}

export interface JsBatchConversionResult {
  successRate: number
  totalTimeMs: number
  convertedValues: Array<string>
  errors: Array<string>
}

export interface JsInstanceStats {
  memoryUsageBytes: number
  executionCount: number
  hotReloadCount: number
  lastExecutionTime?: string
  ffiCallCount: number
  errorCount: number
  uptimeMs: number
}

export interface JsFFIStats {
  totalHostBindings: number
  totalWasmExports: number
  totalCalls: number
  successfulCalls: number
  failedCalls: number
  averageCallTimeMs: number
}

export interface JsConversionStats {
  totalConversions: number
  cacheHits: number
  cacheMisses: number
  successfulConversions: number
  failedConversions: number
  averageConversionTimeMs: number
}

export interface JsInstanceManagerConfig {
  maxInstances: number
  memoryLimitMb: number
  executionTimeoutMs: number
  enableHotReload: boolean
  preserveStateOnReload: boolean
  enableDebugging: boolean
}

export interface JsInstanceCreationResult {
  success: boolean
  instanceId?: string
  memoryDeltaBytes: number
  durationMs: number
  error?: string
}

export interface JsMemoryViewConfig {
  offset: number
  size: number
  viewType: string
}

export interface JsMemoryView {
  success: boolean
  viewId?: string
  offset: number
  size: number
  viewType: string
  error?: string
}

export interface JsMemoryCompactionResult {
  success: boolean
  bytesFreed: number
  fragmentationBefore: number
  fragmentationAfter: number
  durationMs: number
}

export interface JsFFIStatePreservation {
  success: boolean
  preservedBindings: Array<string>
  preservedStateSize: number
  error?: string
}

export interface JsHostFunctionConfig {
  name: string
  bindingType: string
  isAsync: boolean
  paramTypes: Array<string>
  resultTypes: Array<string>
  preserveState: boolean
}

export interface JsTypeMapping {
  sourceType: string
  targetType: string
  conversionFunction: string
  isLossy: boolean
  validationRequired: boolean
}

export class WasmNapiBindings {
  constructor()
  compileModule(moduleJson: string): Promise<JsWasmModule>
  instantiateModule(instanceId: string, wasmBytecode: Buffer, imports?: object): Promise<JsExecutionResult>
  callFunction(instanceId: string, functionName: string, args: Array<string>): Promise<JsExecutionResult>
  allocateMemory(instanceId: string, size: number, allocationType: string): JsMemoryAllocation
  writeMemory(instanceId: string, offset: number, data: Buffer): boolean
  readMemory(instanceId: string, offset: number, size: number): Buffer
  freeMemory(instanceId: string, allocationId: string): boolean
  registerFfiBinding(instanceId: string, bindingConfig: JsFFIBinding): boolean
  callFfiFunction(instanceId: string, functionName: string, args: Array<string>): Promise<JsFFICallResult>
  getFfiBindings(instanceId: string): Array<JsFFIBinding>
  hotReloadModule(instanceId: string, newWasmBytecode: Buffer, preserveState?: boolean): Promise<JsHotReloadResult>
  getMemoryStats(instanceId: string): JsMemoryStats
  getInstanceStats(instanceId: string): JsInstanceStats
  getFfiStats(): JsFFIStats
  convertJsToWasm(conversion: JsValueConversion): string
  batchConvertValues(conversions: Array<JsValueConversion>): JsBatchConversionResult
  compactMemory(instanceId: string): boolean
  garbageCollect(instanceId: string): number
  disposeInstance(instanceId: string): boolean
  listInstances(): Array<string>
  setOptimizationLevel(level: string): void
}

export class WasmInstanceManager {
  constructor(config: JsInstanceManagerConfig)
  createInstance(instanceId: string, wasmBytecode: Buffer, imports?: object): Promise<JsInstanceCreationResult>
  executeFunction(instanceId: string, functionName: string, args: Array<string>): Promise<JsExecutionResult>
  hotReloadInstance(instanceId: string, newWasmBytecode: Buffer): Promise<JsHotReloadResult>
  removeInstance(instanceId: string): boolean
  listInstances(): Array<string>
  getInstanceStatistics(instanceId: string): JsInstanceStats
  setOptimizationLevel(level: string): void
}

export class WasmMemoryManager {
  constructor()
  allocateMemory(instanceId: string, size: number, allocationType: string): JsMemoryAllocation
  writeMemory(instanceId: string, offset: number, data: Buffer): JsMemoryAllocation
  readMemory(instanceId: string, offset: number, size: number): Buffer
  createMemoryView(instanceId: string, offset: number, size: number, viewType: string): JsMemoryView
  getMemoryStats(instanceId: string): JsMemoryStats
  compactMemory(instanceId: string): JsMemoryCompactionResult
  garbageCollect(instanceId: string): number
  freeAllocation(instanceId: string, allocationId: string): boolean
  listAllocations(instanceId: string): Array<string>
  removeMemoryView(viewId: string): boolean
  listMemoryViews(): Array<string>
}

export class FFIBridge {
  constructor()
  // biome-ignore lint/complexity/noBannedTypes: <explanation>
  registerHostFunction(config: JsHostFunctionConfig, hostFunction: Function): boolean
  callHostFunction(functionName: string, args: Array<string>, instanceId: string): Promise<JsFFICallResult>
  registerWasmExport(instanceId: string, exportName: string, exportType: string): boolean
  callWasmExport(instanceId: string, exportName: string, args: Array<string>): Promise<JsFFICallResult>
  preserveFfiState(instanceId: string): JsFFIStatePreservation
  restoreFfiState(instanceId: string, preservedBindings: Array<string>): boolean
  getFfiStats(): JsFFIStats
  listHostFunctions(): Array<string>
  getHostFunctionConfig(functionName: string): JsHostFunctionConfig
  removeHostFunction(functionName: string): boolean
  getFunctionCallStats(functionName: string): JsFFICallResult
  clearCallStatistics(): void
  hasHostFunction(functionName: string): boolean
  getFunctionCount(): number
}

export class ValueConverter {
  constructor()
  jsToWasm(sourceValue: string, targetType: string): string
  wasmToJs(sourceValue: string, sourceType: string): string
  batchConvert(conversions: Array<JsValueConversion>): JsBatchConversionResult
  registerTypeMapping(mappingName: string, sourceType: string, targetType: string, conversionFunction: string): boolean
  getConversionStats(): JsConversionStats
  clearCache(): number
  configureCache(enabled: boolean, maxSize: number): void
  getCacheStats(): object
  validateConversion(sourceType: string, targetType: string): boolean
  listSupportedConversions(): Array<string>
  resetStatistics(): void
  getTypeMapping(mappingName: string): JsTypeMapping
  removeTypeMapping(mappingName: string): boolean
  listTypeMappings(): Array<string>
}

// Convenience runtime creation function
export interface WasmRuntimeConfig {
  maxInstances?: number
  memoryLimitMb?: number
  executionTimeoutMs?: number
  enableHotReload?: boolean
  preserveStateOnReload?: boolean
  enableDebugging?: boolean
}

export interface WasmRuntime {
  instanceManager: WasmInstanceManager
  memoryManager: WasmMemoryManager
  ffiBridge: FFIBridge
  valueConverter: ValueConverter
  napiBindings: WasmNapiBindings
  
  // Convenience methods
  createInstance(instanceId: string, wasmBytecode: Buffer, imports?: object): Promise<JsInstanceCreationResult>
  executeFunction(instanceId: string, functionName: string, args?: Array<string>): Promise<JsExecutionResult>
  hotReload(instanceId: string, newWasmBytecode: Buffer): Promise<JsHotReloadResult>
  allocateMemory(instanceId: string, size: number, type?: string): JsMemoryAllocation
  writeMemory(instanceId: string, offset: number, data: Buffer): JsMemoryAllocation
  readMemory(instanceId: string, offset: number, size: number): Buffer
  // biome-ignore lint/complexity/noBannedTypes: <explanation>
  registerHostFunction(config: JsHostFunctionConfig, hostFunction: Function): boolean
  callHostFunction(functionName: string, args: Array<string>, instanceId: string): Promise<JsFFICallResult>
  convertValue(sourceValue: string, sourceType: string, targetType: string): string
  getStats(): {
    instances: Array<string>
    ffi: JsFFIStats
    conversions: JsConversionStats
  }
  cleanup(): void
}

export function createWasmRuntime(config?: WasmRuntimeConfig): WasmRuntime

export declare const version: string