//! JavaScript code generation from MIR IR
//!
//! This module implements JavaScript compilation from MIR IR, including:
//! - JavaScript code generation with multiple target versions
//! - Optimization and minification
//! - Source map generation support
//! - OpenTelemetry instrumentation preservation

use mir_ast::{Module, Statement, Expression, MetricType, LogLevel};
use mir_types::Value;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// JavaScript code generator with configurable targets and optimization
pub struct JsCodeGenerator {
    target: JsTarget,
    minify: bool,
    optimize: bool,
    preserve_comments: bool,
    emit_source_maps: bool,
    runtime_checks: bool,
}

/// JavaScript target versions
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum JsTarget {
    ES5,
    ES2015,
    ES2018,
    ES2020,
    ES2022,
    ESNext,
}

/// JavaScript generation options
#[derive(Debug, Clone)]
pub struct JsGenerationOptions {
    pub target: JsTarget,
    pub minify: bool,
    pub optimize: bool,
    pub preserve_comments: bool,
    pub emit_source_maps: bool,
    pub runtime_checks: bool,
    pub module_format: ModuleFormat,
}

/// Module output formats
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ModuleFormat {
    CommonJS,
    ES6,
    UMD,
    IIFE,
}

/// Generated JavaScript output
#[derive(Debug, Clone)]
pub struct JsOutput {
    pub code: String,
    pub source_map: Option<String>,
    pub declarations: Option<String>, // TypeScript declarations
    pub metadata: JsMetadata,
}

/// Metadata about the generated JavaScript
#[derive(Debug, Clone)]
pub struct JsMetadata {
    pub module_name: String,
    pub target: JsTarget,
    pub minified: bool,
    pub optimized: bool,
    pub exports: Vec<String>,
    pub imports: Vec<String>,
    pub functions: Vec<String>,
    pub otel_instrumented: bool,
}

impl Default for JsCodeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl JsCodeGenerator {
    /// Create a new JavaScript code generator with default settings
    pub fn new() -> Self {
        JsCodeGenerator {
            target: JsTarget::ES2020,
            minify: false,
            optimize: true,
            preserve_comments: false,
            emit_source_maps: true,
            runtime_checks: true,
        }
    }

    /// Create a new generator with custom options
    pub fn with_options(options: JsGenerationOptions) -> Self {
        JsCodeGenerator {
            target: options.target,
            minify: options.minify,
            optimize: options.optimize,
            preserve_comments: options.preserve_comments,
            emit_source_maps: options.emit_source_maps,
            runtime_checks: options.runtime_checks,
        }
    }

    /// Generate JavaScript code from a MIR module
    pub fn generate(&self, module: &Module) -> Result<JsOutput, CodegenError> {
        let mut context = CodegenContext::new(module, self.target);
        
        // Generate module header
        let mut code = self.generate_module_header(&mut context)?;
        
        // Generate imports
        code.push_str(&self.generate_imports(module, &mut context)?);
        
        // Generate module body
        code.push_str(&self.generate_module_body(module, &mut context)?);
        
        // Generate exports
        code.push_str(&self.generate_exports(module, &mut context)?);
        
        // Generate module footer
        code.push_str(&self.generate_module_footer(&mut context)?);
        
        // Apply optimizations
        if self.optimize {
            code = self.optimize_code(code)?;
        }
        
        // Apply minification
        if self.minify {
            code = self.minify_code(code)?;
        }
        
        let metadata = JsMetadata {
            module_name: module.name.clone(),
            target: self.target,
            minified: self.minify,
            optimized: self.optimize,
            exports: context.exports,
            imports: context.imports,
            functions: context.functions,
            otel_instrumented: context.has_otel_instrumentation,
        };
        
        Ok(JsOutput {
            code,
            source_map: None, // Will be generated separately
            declarations: None, // Will be generated by TypeScript generator
            metadata,
        })
    }

    /// Generate module header with runtime setup
    fn generate_module_header(&self, context: &mut CodegenContext) -> Result<String, CodegenError> {
        let mut header = String::new();
        
        // Add file header comment
        if self.preserve_comments {
            header.push_str(&format!(
                "/**\n * Generated JavaScript for MIR module: {}\n * Target: {:?}\n * Generated at: {}\n */\n\n",
                context.module_name,
                self.target,
                chrono::Utc::now().format("%Y-%m-%d %H:%M:%S UTC")
            ));
        }
        
        // Add strict mode for modern targets
        if matches!(self.target, JsTarget::ES2015 | JsTarget::ES2018 | JsTarget::ES2020 | JsTarget::ES2022 | JsTarget::ESNext) {
            header.push_str("'use strict';\n\n");
        }
        
        // Add MIR runtime helpers
        header.push_str(&self.generate_runtime_helpers()?);
        
        Ok(header)
    }

    /// Generate runtime helper functions
    fn generate_runtime_helpers(&self) -> Result<String, CodegenError> {
        let mut helpers = String::new();
        
        // Type checking helpers
        if self.runtime_checks {
            helpers.push_str(r#"
// MIR Runtime Type Helpers
const MIR = {
    typeCheck: (value, expectedType) => {
        // Runtime type checking implementation
        return true; // Simplified for now
    },
    
    structuralEquals: (a, b) => {
        if (a === b) return true;
        if (a == null || b == null) return false;
        if (typeof a !== typeof b) return false;
        
        if (typeof a === 'object') {
            const keysA = Object.keys(a);
            const keysB = Object.keys(b);
            if (keysA.length !== keysB.length) return false;
            
            for (let key of keysA) {
                if (!keysB.includes(key)) return false;
                if (!MIR.structuralEquals(a[key], b[key])) return false;
            }
            return true;
        }
        
        return a === b;
    },
    
    contentHash: (value) => {
        // Simplified content hashing
        return JSON.stringify(value).split('').reduce((a, b) => {
            a = ((a << 5) - a) + b.charCodeAt(0);
            return a & a;
        }, 0).toString(16);
    }
};

"#);
        }
        
        // OpenTelemetry helpers if needed
        helpers.push_str(r#"
// OpenTelemetry Integration
const OTEL = {
    createSpan: (name, attributes = {}) => {
        // Integration with OpenTelemetry API
        if (typeof window !== 'undefined' && window.otel) {
            return window.otel.trace.getActiveTracer().startSpan(name, { attributes });
        } else if (typeof global !== 'undefined' && global.otel) {
            return global.otel.trace.getActiveTracer().startSpan(name, { attributes });
        }
        // Fallback no-op span
        return {
            setAttributes: () => {},
            addEvent: () => {},
            end: () => {},
            recordException: () => {}
        };
    },
    
    withSpan: (span, fn) => {
        try {
            return fn();
        } finally {
            span.end();
        }
    },
    
    recordMetric: (type, name, value, labels = {}) => {
        // Integration with OpenTelemetry metrics
        if (typeof console !== 'undefined') {
            console.log(`[METRIC] ${type}:${name} = ${value}`, labels);
        }
    },
    
    logEvent: (level, message, attributes = {}) => {
        // Structured logging
        const logEntry = {
            timestamp: new Date().toISOString(),
            level,
            message,
            attributes
        };
        
        if (typeof console !== 'undefined') {
            console[level.toLowerCase()] || console.log(JSON.stringify(logEntry));
        }
    }
};

"#);
        
        Ok(helpers)
    }

    /// Generate import statements
    fn generate_imports(&self, module: &Module, context: &mut CodegenContext) -> Result<String, CodegenError> {
        let mut imports = String::new();
        
        for import in &module.imports {
            context.imports.push(import.module_path.clone());
            
            match self.target {
                JsTarget::ES5 => {
                    // CommonJS style imports for ES5
                    imports.push_str(&format!("var {} = require('{}');\n", 
                        self.sanitize_identifier(&import.module_path),
                        import.module_path
                    ));
                }
                _ => {
                    // ES6+ style imports
                    let import_items: Vec<String> = import.imported_items.iter()
                        .map(|item| {
                            if let Some(alias) = &item.alias {
                                format!("{} as {}", item.name, alias)
                            } else {
                                item.name.clone()
                            }
                        })
                        .collect();
                    
                    if import_items.is_empty() {
                        imports.push_str(&format!("import '{}';\n", import.module_path));
                    } else {
                        imports.push_str(&format!("import {{ {} }} from '{}';\n", 
                            import_items.join(", "),
                            import.module_path
                        ));
                    }
                }
            }
        }
        
        if !imports.is_empty() {
            imports.push('\n');
        }
        
        Ok(imports)
    }

    /// Generate the main module body
    fn generate_module_body(&self, module: &Module, context: &mut CodegenContext) -> Result<String, CodegenError> {
        let mut body = String::new();
        
        for statement in &module.statements {
            body.push_str(&self.generate_statement(statement, context)?);
            body.push('\n');
        }
        
        Ok(body)
    }

    /// Generate a single statement
    fn generate_statement(&self, statement: &Statement, context: &mut CodegenContext) -> Result<String, CodegenError> {
        match statement {
            Statement::Expression { expression, .. } => {
                Ok(format!("{};", self.generate_expression(expression, context)?))
            }
            
            Statement::VariableDeclaration { name, value, .. } => {
                let var_keyword = match self.target {
                    JsTarget::ES5 => "var",
                    _ => "const",
                };
                
                if let Some(value_expr) = value {
                    Ok(format!("{} {} = {};", 
                        var_keyword, 
                        self.sanitize_identifier(name),
                        self.generate_expression(value_expr, context)?
                    ))
                } else {
                    Ok(format!("{} {};", var_keyword, self.sanitize_identifier(name)))
                }
            }
            
            Statement::FunctionDeclaration { name, parameters, body, .. } => {
                context.functions.push(name.clone());
                
                let params = parameters.iter()
                    .map(|p| self.sanitize_identifier(p))
                    .collect::<Vec<_>>()
                    .join(", ");
                
                let mut func_body = String::new();
                for stmt in body {
                    func_body.push_str("  ");
                    func_body.push_str(&self.generate_statement(stmt, context)?);
                    func_body.push('\n');
                }
                
                Ok(format!("function {}({}) {{\n{}}}", 
                    self.sanitize_identifier(name),
                    params,
                    func_body
                ))
            }
            
            Statement::StartSpan { name, attributes, body, .. } => {
                context.has_otel_instrumentation = true;
                
                let attrs = self.generate_attributes_object(attributes)?;
                let mut span_body = String::new();
                
                for stmt in body {
                    span_body.push_str("  ");
                    span_body.push_str(&self.generate_statement(stmt, context)?);
                    span_body.push('\n');
                }
                
                Ok(format!(
                    "OTEL.withSpan(OTEL.createSpan('{}', {}), () => {{\n{}}});",
                    name, attrs, span_body
                ))
            }
            
            Statement::RecordMetric { metric_type, name, value, labels, .. } => {
                context.has_otel_instrumentation = true;
                
                let metric_type_str = match metric_type {
                    MetricType::Counter => "counter",
                    MetricType::Gauge => "gauge", 
                    MetricType::Histogram => "histogram",
                };
                
                let labels_obj = self.generate_attributes_object(labels)?;
                
                Ok(format!(
                    "OTEL.recordMetric('{}', '{}', {}, {});",
                    metric_type_str,
                    name,
                    self.generate_expression(value, context)?,
                    labels_obj
                ))
            }
            
            Statement::LogEvent { level, message, attributes, .. } => {
                context.has_otel_instrumentation = true;
                
                let level_str = match level {
                    LogLevel::Trace => "trace",
                    LogLevel::Debug => "debug",
                    LogLevel::Info => "info",
                    LogLevel::Warn => "warn",
                    LogLevel::Error => "error",
                };
                
                let attrs_obj = self.generate_attributes_object(attributes)?;
                
                Ok(format!(
                    "OTEL.logEvent('{}', '{}', {});",
                    level_str, message, attrs_obj
                ))
            }
            
            _ => Err(CodegenError::UnsupportedFeature(
                format!("Statement type not yet implemented: {:?}", statement)
            ))
        }
    }

    /// Generate an expression
    fn generate_expression(&self, expression: &Expression, context: &mut CodegenContext) -> Result<String, CodegenError> {
        match expression {
            Expression::Literal { value, .. } => {
                self.generate_literal(value)
            }
            
            Expression::Identifier { name, .. } => {
                Ok(self.sanitize_identifier(name))
            }
            
            Expression::FunctionCall { function, arguments, .. } => {
                let func_expr = self.generate_expression(function, context)?;
                let args: Result<Vec<String>, CodegenError> = arguments.iter()
                    .map(|arg| self.generate_expression(arg, context))
                    .collect();
                
                Ok(format!("{}({})", func_expr, args?.join(", ")))
            }
            
            Expression::CreateSpan { name, attributes, parent_span, .. } => {
                context.has_otel_instrumentation = true;
                
                let attrs = self.generate_attributes_object(attributes)?;
                
                if let Some(parent) = parent_span {
                    let parent_expr = self.generate_expression(parent, context)?;
                    Ok(format!(
                        "OTEL.createSpan('{}', {}, {})",
                        name, attrs, parent_expr
                    ))
                } else {
                    Ok(format!("OTEL.createSpan('{}', {})", name, attrs))
                }
            }
            
            Expression::SetSpanAttribute { span, key, value, .. } => {
                context.has_otel_instrumentation = true;
                
                let span_expr = self.generate_expression(span, context)?;
                let value_js = self.generate_literal(value)?;
                
                Ok(format!(
                    "{}.setAttributes({{ '{}': {} }})",
                    span_expr, key, value_js
                ))
            }
            
            Expression::AddSpanEvent { span, name, attributes, .. } => {
                context.has_otel_instrumentation = true;
                
                let span_expr = self.generate_expression(span, context)?;
                let attrs = self.generate_attributes_object(attributes)?;
                
                Ok(format!(
                    "{}.addEvent('{}', {})",
                    span_expr, name, attrs
                ))
            }
            
            Expression::GetTraceContext { .. } => {
                context.has_otel_instrumentation = true;
                Ok("OTEL.getActiveContext()".to_string())
            }
            
            Expression::SetTraceContext { context: ctx_expr, .. } => {
                context.has_otel_instrumentation = true;
                let ctx = self.generate_expression(ctx_expr, context)?;
                Ok(format!("OTEL.setActiveContext({})", ctx))
            }
        }
    }

    /// Generate a literal value
    fn generate_literal(&self, value: &Value) -> Result<String, CodegenError> {
        match value {
            Value::I32(v) => Ok(v.to_string()),
            Value::I64(v) => Ok(v.to_string()),
            Value::I128(v) => Ok(format!("{}n", v)), // BigInt literal
            Value::U32(v) => Ok(v.to_string()),
            Value::U64(v) => Ok(v.to_string()),
            Value::U128(v) => Ok(format!("{}n", v)), // BigInt literal
            Value::F32(v) => {
                if v.is_nan() {
                    Ok("NaN".to_string())
                } else if v.is_infinite() {
                    if v.is_sign_positive() {
                        Ok("Infinity".to_string())
                    } else {
                        Ok("-Infinity".to_string())
                    }
                } else {
                    Ok(v.to_string())
                }
            }
            Value::F64(v) => {
                if v.is_nan() {
                    Ok("NaN".to_string())
                } else if v.is_infinite() {
                    if v.is_sign_positive() {
                        Ok("Infinity".to_string())
                    } else {
                        Ok("-Infinity".to_string())
                    }
                } else {
                    Ok(v.to_string())
                }
            }
            Value::Bool(v) => Ok(v.to_string()),
            Value::String(v) => Ok(format!("'{}'", v.replace('\'', "\\'"))),
            Value::Null => Ok("null".to_string()),
            _ => Err(CodegenError::UnsupportedFeature(
                format!("Literal type not yet implemented: {:?}", value)
            ))
        }
    }

    /// Generate an attributes object from a HashMap
    fn generate_attributes_object(&self, attributes: &HashMap<String, Value>) -> Result<String, CodegenError> {
        if attributes.is_empty() {
            return Ok("{}".to_string());
        }
        
        let attrs: Result<Vec<String>, CodegenError> = attributes.iter()
            .map(|(key, value)| {
                let value_js = self.generate_literal(value)?;
                Ok(format!("'{}': {}", key, value_js))
            })
            .collect();
        
        Ok(format!("{{ {} }}", attrs?.join(", ")))
    }

    /// Generate export statements
    fn generate_exports(&self, module: &Module, context: &mut CodegenContext) -> Result<String, CodegenError> {
        let mut exports = String::new();
        
        for export in &module.exports {
            context.exports.push(export.name.clone());
            
            match self.target {
                JsTarget::ES5 => {
                    // CommonJS style exports
                    exports.push_str(&format!(
                        "module.exports.{} = {};\n",
                        self.sanitize_identifier(&export.name),
                        self.sanitize_identifier(&export.name)
                    ));
                }
                _ => {
                    // ES6+ style exports
                    exports.push_str(&format!(
                        "export {{ {} }};\n",
                        self.sanitize_identifier(&export.name)
                    ));
                }
            }
        }
        
        Ok(exports)
    }

    /// Generate module footer
    fn generate_module_footer(&self, _context: &mut CodegenContext) -> Result<String, CodegenError> {
        Ok("\n".to_string())
    }

    /// Apply code optimizations
    fn optimize_code(&self, code: String) -> Result<String, CodegenError> {
        // Simple optimizations - in a full implementation this would be more sophisticated
        let mut optimized = code;
        
        // Remove unnecessary whitespace (but preserve functionality)
        if self.minify {
            optimized = optimized
                .lines()
                .map(|line| line.trim())
                .filter(|line| !line.is_empty())
                .collect::<Vec<_>>()
                .join("\n");
        }
        
        Ok(optimized)
    }

    /// Apply code minification
    fn minify_code(&self, code: String) -> Result<String, CodegenError> {
        // Simple minification - remove extra whitespace and comments
        let mut minified = code;
        
        // Remove single-line comments (but preserve URLs and other important comments)
        minified = minified
            .lines()
            .map(|line| {
                if let Some(pos) = line.find("//") {
                    // Don't remove if it's part of a URL
                    if !line[..pos].contains("http") {
                        &line[..pos]
                    } else {
                        line
                    }
                } else {
                    line
                }
            })
            .collect::<Vec<_>>()
            .join("\n");
        
        // Remove extra whitespace
        minified = minified
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ");
        
        Ok(minified)
    }

    /// Sanitize JavaScript identifiers
    fn sanitize_identifier(&self, name: &str) -> String {
        // Replace invalid characters with underscores
        name.chars()
            .map(|c| if c.is_alphanumeric() || c == '_' || c == '$' { c } else { '_' })
            .collect()
    }

    /// Set the JavaScript target version
    pub fn set_target(&mut self, target: JsTarget) {
        self.target = target;
    }

    /// Enable or disable minification
    pub fn set_minify(&mut self, minify: bool) {
        self.minify = minify;
    }

    /// Enable or disable optimization
    pub fn set_optimize(&mut self, optimize: bool) {
        self.optimize = optimize;
    }

    /// Enable or disable source map generation
    pub fn set_emit_source_maps(&mut self, emit: bool) {
        self.emit_source_maps = emit;
    }

    /// Enable or disable runtime type checks
    pub fn set_runtime_checks(&mut self, checks: bool) {
        self.runtime_checks = checks;
    }
}

/// Context for code generation
struct CodegenContext {
    module_name: String,
    #[allow(dead_code)]
    target: JsTarget,
    exports: Vec<String>,
    imports: Vec<String>,
    functions: Vec<String>,
    has_otel_instrumentation: bool,
}

impl CodegenContext {
    fn new(module: &Module, target: JsTarget) -> Self {
        CodegenContext {
            module_name: module.name.clone(),
            target,
            exports: Vec::new(),
            imports: Vec::new(),
            functions: Vec::new(),
            has_otel_instrumentation: false,
        }
    }
}

impl Default for JsGenerationOptions {
    fn default() -> Self {
        JsGenerationOptions {
            target: JsTarget::ES2020,
            minify: false,
            optimize: true,
            preserve_comments: false,
            emit_source_maps: true,
            runtime_checks: true,
            module_format: ModuleFormat::ES6,
        }
    }
}

/// Errors that can occur during JavaScript code generation
#[derive(Debug, Clone)]
pub enum CodegenError {
    UnsupportedFeature(String),
    InvalidModule(String),
    InvalidExpression(String),
    InvalidStatement(String),
    OptimizationFailed(String),
    MinificationFailed(String),
    SourceMapGenerationFailed(String),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodegenError::UnsupportedFeature(msg) => write!(f, "Unsupported feature: {}", msg),
            CodegenError::InvalidModule(msg) => write!(f, "Invalid module: {}", msg),
            CodegenError::InvalidExpression(msg) => write!(f, "Invalid expression: {}", msg),
            CodegenError::InvalidStatement(msg) => write!(f, "Invalid statement: {}", msg),
            CodegenError::OptimizationFailed(msg) => write!(f, "Optimization failed: {}", msg),
            CodegenError::MinificationFailed(msg) => write!(f, "Minification failed: {}", msg),
            CodegenError::SourceMapGenerationFailed(msg) => write!(f, "Source map generation failed: {}", msg),
        }
    }
}

impl std::error::Error for CodegenError {}